### ISSUE TITLE
Correção

### ISSUE THREAD

**Issue by glandre** [joorgelm/Engenharia-de-Software#7]
dúvidas:
	rf1 - dias de trabalho: por mês?

correcoes:
	arquivo "Pontos por Função.pdf" está conceitualmente errado.
	arquivo "Documento com Pontos por Função.pdf" está correto.

correcao:
	Os ALIs "clientes", "entregadores" e "funcionarios" podem ser unificados (1 ALI com 10 TED, acrescentando o campo tipo_pessoa por exemplo).
		Criar tabela: "Usuário" e "Tipo de Usuário" (2 tabelas, ou seja, 2 TAR)
	
	Nesse sentido, os requisitos rf3, rf2 e rf1 usam o mesmo ALI (economizando pontuacao) e o rf4 seria apenas 2 TAR.
	rf16, rf15, rf14 e rf13 deve são o mesmo requisito, devem ser colocados juntos. (Continuar considerando a SE.) 
	(Ator principal desse requisito é o entregador)

	rn01: Omitir o termo "chave primária".

**Comment by carolpraxedes** [comment]
Alterações feitas:
RF01 e RF02: dias de trabalho - por semana;
ALIs "clientes, "entregadores" e "funcionários" unificados (1 ALI com 1 TER e 10 TEDs - campo "tipo de usuário" adicionado) - deixei apenas no RF01;
RF04: 2 TAR e 2 TED (entendi que a correção "criar tabela" se referia a esse requisito, mas não tenho certeza... se for outra coisa, aguardo resposta);
RN01: termo "chave primária" omitido.

[Documento com Pontos por Função.docx](https://github.com/joorgelm/Engenharia-de-Software/files/457977/Documento.com.Pontos.por.Funcao.docx)

Falta juntar RF13, RF15, RF15 e RF16

**Comment by carolpraxedes** [comment]
RF13, RF14, RF15 e RF16 transformados em RF13 e RF14.

[Documento.com.Pontos.por.Funcao.docx](https://github.com/joorgelm/Engenharia-de-Software/files/471954/Documento.com.Pontos.por.Funcao.docx)

Pontos por função recalculados e ajustados.
