### ISSUE TITLE
Atualizar Estimativa

### ISSUE THREAD

**Issue by glandre** [joorgelm/Engenharia-de-Software#8]
Ao invés de colocar a hora direto:
- Estimar quantos Pontos por Função a equipe consegue entregar por hora (ou por semana) e explicitar isso em algum documento (Pode ser algo como "Planejamento").

**Comment by carolpraxedes** [comment]
Product Backlog atualizado (com PF ao invés de horas).
Gráfico Burndown criado e atualizado.

**Comment by carolpraxedes** [comment]
Estimativa explicita: Documento "Planejamento" submetido ao repositório.
